services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/etc:/etc/grafana:ro
    environment:
      - GF_SECURITY_ADMIN_USER=uwfe
      - GF_SECURITY_ADMIN_PASSWORD=uwfepassword
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      
volumes:
  grafana-storage: